name: wiki-bert
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pylint
  - pip
  - pip:
    - ipdb
